# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import ledbillboard.references.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron', models.CharField(help_text="'0 * * * *' that run in every hour", max_length=120, validators=[ledbillboard.references.models.validate_cron], verbose_name='Cron command')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
    ]
