# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import ledbillboard.references.models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='cron',
            field=models.CharField(help_text='0 * * * * that run in every hour.', max_length=120, validators=[ledbillboard.references.models.validate_cron], verbose_name='Cron command'),
        ),
    ]
