# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import ledbillboard.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', ledbillboard.account.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_lessor',
            field=models.BooleanField(default=False, verbose_name='Lessor status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=32, validators=[ledbillboard.account.models.NamesValidator(message='Enter a valid first name. This value may contain only letters.')], verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=32, validators=[ledbillboard.account.models.NamesValidator(message='Enter a valid last name. This value may contain only letters.')], verbose_name='Last name'),
        ),
    ]
