# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170418_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_lessor',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as lessor.', verbose_name='Lessor status'),
        ),
    ]
