# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fancy_cronfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profileauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileauth.User')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', fancy_cronfield.fields.CronField(max_length=120)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.Playlist')),
            ],
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.Playlist'),
        ),
    ]
