# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fancy_cronfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('duration', models.FloatField(default=0, verbose_name='Duration')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Upload time')),
                ('is_approve', models.BooleanField(default=False, verbose_name='Is approve')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media items',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', fancy_cronfield.fields.CronField(max_length=120, verbose_name='Schedule')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board', verbose_name='Billboard')),
                ('media', models.ManyToManyField(to='playlist.Media', verbose_name='Media items')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlist items',
            },
        ),
    ]
