# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediacontent', '0001_initial'),
        ('board', '0001_initial'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board', verbose_name='Billboard')),
                ('media', models.ManyToManyField(blank=True, to='mediacontent.Media', verbose_name='Media items')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.Schedule', verbose_name='Schedule')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlist items',
            },
        ),
    ]
