"""
Django settings for ledbillboard project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import ledbillboard

from django.utils.translation import ugettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'w0mm19(^7m=7y72^@a*@@n5q9m9oidh5ks0n%c_3#a767xqky^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'grappelli.dashboard',
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'graphene_django',
    'ledbillboard',
    'ledbillboard.account',
    'ledbillboard.playlist',
    'ledbillboard.board',
    'ledbillboard.mediacontent',
    'ledbillboard.company',
    'ledbillboard.references',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ledbillboard.urls'

LOADERS = (
    ('django.template.loaders.cached.Loader', (
        'django.template.loaders.app_directories.Loader',
    )),
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'ledbillboard/templates')
        ],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'debug': DEBUG,
            'loaders': LOADERS,
        },
    },
]

WSGI_APPLICATION = 'ledbillboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'ledbillboard',
        'USER': 'postgres',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '__static'

# Django authentication
AUTH_USER_MODEL = 'account.user'

# Localization
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'ledbillboard/locale')
]

LANGUAGES = [
    ('en', _('English')),
    ('ru', _('Russian')),
]

# Grapelli http://django-grappelli.readthedocs.org/en/latest/
GRAPPELLI_INDEX_DASHBOARD = 'ledbillboard.dashboard.CustomIndexDashboard'
GRAPPELLI_ADMIN_TITLE = 'Ledbillboard'

# WebDav
DEFAULT_FILE_STORAGE = 'django_webdav_storage.storage.WebDavStorage'
WEBDAV_URL = 'http://admin:admin@localhost:8135/'
WEBDAV_PUBLIC_URL = 'http://localhost/'
WEBDAV_LISTING_BACKEND = 'django_webdav_storage.listing.nginx_autoindex'

# GraphQL
GRAPHENE = {
    'SCHEMA': 'ledbillboard.schema.schema'
}

# Override settings on config/settings.py
SETTINGS_OVERRIDES = os.environ.get('SETTINGS_OVERRIDES', None)
if SETTINGS_OVERRIDES is not None and os.path.exists(SETTINGS_OVERRIDES):
    settings = open(SETTINGS_OVERRIDES).read()
    exec(settings)
