# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170418_1401'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.User', verbose_name='User'),
            preserve_default=False,
        ),
    ]
