# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='code',
        ),
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
