# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20170427_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together=set([('name', 'slug')]),
        ),
    ]
