# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import ledbillboard.mediacontent.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacontent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=ledbillboard.mediacontent.models.get_upload_path, verbose_name='File'),
        ),
    ]
